### ISSUE TITLE
node_moduleはチェック対象外で良いのではないか。

### ISSUE THREAD

**Issue by sizer** [dm-production/dm_linters#2]
`rubocop --auto-correct`した際にnode_module配下を修正してしまうのはよろしくないので。

[`config/.rubocop.yml`のこのへん](https://github.com/dm-production/dm_linters/blob/v0.0.4/config/.rubocop.yml#L5-L7)で

```yml
AllCops:
  Exclude:
    - 'node_modules/**/*' # new!!
```

こうしたい。
